### ISSUE TITLE
Modified slug gets updated once again when record form is reopened

### ISSUE THREAD

**Issue by benosman** [dimitrov-adrian/directus-extension-wpslug-interface#1]
Hey @dimitrov-adrian 

Thanks for creating this extension, it looks to be very handy!

I am testing it out on an instance and I noticed a behaviour which I think is a bug, or at least could be improved, here are the steps to reproduce:

1. Add slug field & interface to collection, set template as another field.
2. Create / edit a record with a custom url, when editing for the first time the interface behaves correctly, after editing, the slug is no longer auto-generated.
3. Save the record with edited slug
4. Reopen the record for editing. 
5. Slug displays the wand button (auto-generate), so `haveChange` is true.
6. Any changes to the field set as template immediately triggers updating the url, so the previous changes are lost.

I think that changes should be persistent when the form is reopened for editing.

I thought it may be a simple fix in `setup()` to instantiate `isTouched` based on `haveChange` but that turned out to only work when the form is loaded for the first time (e.g. a full page refresh). When following a link from inside the admin app, `props.value` is `null` in `setup()` and gets populated later on.

I have a working version, but I haven't created a pull request as there is likely a better way to accomplish this:
https://github.com/benosman/directus-extension-wpslug-interface/commit/1948e03400429329ec5372aecff5ac99f9a0ad96

Note: my fork is modified to work on a slightly outdated version of directus, but the actual vue component was the same as your v1.0.0

**Comment by dimitrov-adrian** [comment]
Yes, I agree it might be confusing in some cases. I also tried your fix, but isn't it in conflicts with the "On update" mode? I am thinking with this, it trying to disable it when the value is set and differs from auto generated one.

**Comment by dimitrov-adrian** [comment]
I am closing this one, as far as I understands, it's completely handled by the on update and on create options from the interface setup

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1009639/167000680-caa02349-fd83-4397-824e-78f85d849401.png">
