### ISSUE TITLE
Slug is not saved to DB

### ISSUE THREAD

**Issue by tejasmaven** [dimitrov-adrian/directus-extension-wpslug-interface#3]
Hi There,

First of all, thank you for this extension. It will save lot of time for slug-related setup to blogging/content related projects.

Now, I have setup Directus 9.8.0 and installed this extension. Issue is, I did configure it correctly but data are not saved to database. Also it does not manages slugs. Example  
BlogTitle1 = blog/blogtitle1
BlogTitle2= blog/blogtitle2
BlogTitle1 = blog/blogtitle1  <- this is issue. it should change to  blog/blogtitle1-1 or something else.

Can you fix and update this package?

**Comment by dimitrov-adrian** [comment]
> BlogTitle1 = blog/blogtitle1 <- this is issue. it should change to blog/blogtitle1-1 or something else.

How this is suppose to be an issue, and why it should be `blog/blogtitle1-1`

Is this the same bug as described in #2?

**Comment by tejasmaven** [comment]
Thank you for responding.

If we have 2 blog/blogtittle1 value then it will be difficult to fetch record when you read data from slug instead of ID. As clean URL we will need domain.com/blog/blogtitle1 or domain.com/blog/blogtitle2 .

**Comment by dimitrov-adrian** [comment]
Oh, I got it. But I am not sure there is a solution here as this is an interface that have the only responsibility to handle data inputs and have nothing to do with the storing logic.

I think you could add unique flag to the field so when Directus tries to store it, you will get an error for value duplication.

**Comment by tejasmaven** [comment]
Thank you for your input. Will have a look based on your input.
