### ISSUE TITLE
Is it supposed to work on v9.15.1/ v9.16.0 ?

### ISSUE THREAD

**Issue by rafaeldsousa** [dimitrov-adrian/directus-extension-wpslug-interface#6]
Have added the field and selected slug as interface, but doesn't seem to be loading as expected.

<img width="601" alt="Screen Shot 2022-08-18 at 5 46 10 PM" src="https://user-images.githubusercontent.com/39249777/185303344-e05c4a98-b670-4de5-8360-dc5a35a15236.png">

**Comment by ishigami** [comment]
@rafaeldsousa did you set the template pointing to the Title field, when you created the slug field?

**Comment by rafaeldsousa** [comment]
@ishigami do I need to ? I've just followed the how to use instructions on the README
```
Create new standard field with String type
For interface select Slug
```
I also can't see an option to set the template in the CMS.

https://user-images.githubusercontent.com/39249777/185516247-6373103a-195c-445f-a1a1-c746fb8ee3f6.mov

**Comment by ishigami** [comment]
Hi @rafaeldsousa 

This is the screenshot of my installation:

![image](https://user-images.githubusercontent.com/2190465/185523534-3de6817d-1099-440a-a5a5-175cc87efad1.png)

Did yout try to reinstall the node_modules?

Sorry my installation is in Portuguese. And I'm using Directus 9.15.1.

**Comment by rafaeldsousa** [comment]
@ishigami II even tried moving the interface to my local interfaces, but that wasn't being registered for some reason. But removed the package and then reinstalled it.
My CMS has just been updated to 9.16.0 (updated today it seems) and these fields don't appear anymore.

No problems about the portuguese, I'm BR as well ;)

**Comment by ishigami** [comment]
Hi @rafaeldsousa.

Try to make the downgrade to 9.15.1. 

I've upgraded today to 9.16.0. But all my fields disappeared. 

Then I did the rollback to 9.15.1 and everything get back to normal.

**Comment by rafaeldsousa** [comment]
@ishigami downgrading to 9.15.1 worked.
I'd suggested that for 9.15.1 the README should be updated to include the template bit on the how to use, as that not very obvious.

For v9.16.0 I guess there were bigger changes to the interface setup that will require further investigation and a proper fix to get it working on this latest verison.

**Comment by ishigami** [comment]
I think the issue with 9.16.0 is not only with directus-extension-wpslug-interface. It affects all the Directus. In the Discord channel more users are experiencing this problem.

**Comment by ishigami** [comment]
Just to update. The version 9.16.1 - released in the next day of this issue - solves the issues in forms.

@rafaeldsousa I suggest you to close this issue if it's OK for you.

**Comment by rafaeldsousa** [comment]
Release 9.16.1 resolves issue. Closing this issue.
